# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chopchop_app', '0003_auto_20190120_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_code', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('current_session', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chairsession',
            name='chair_code',
        ),
        migrations.RemoveField(
            model_name='chairsession',
            name='status',
        ),
        migrations.AddField(
            model_name='chairsession',
            name='chair',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='chopchop_app.Chair'),
            preserve_default=False,
        ),
    ]
